export const FETCH_ALL_RECIPES_PENDING = 'FETCH_ALL_RECIPES_PENDING'
export const FETCH_ALL_RECIPES_SUCCESS = 'FETCH_ALL_RECIPES_SUCCESS'
export const FETCH_ALL_RECIPES_FAILED = 'FETCH_ALL_RECIPES_FAILED'

export const FETCH_ONE_RECIPE_PENDING = 'FETCH_ONE_RECIPE_PENDING'
export const FETCH_ONE_RECIPE_SUCCESS = 'FETCH_ONE_RECIPE_SUCCESS'
export const FETCH_ONE_RECIPE_FAILED = 'FETCH_ONE_RECIPE_FAILED'

export const ADD_RECIPE_PENDING = 'ADD_RECIPE_PENDING'
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS'
export const ADD_RECIPE_FAILED = 'ADD_RECIPE_FAILED'

export const REMOVE_RECIPE_PENDING = 'REMOVE_RECIPE_PENDING'
export const REMOVE_RECIPE_SUCCESS = 'REMOVE_RECIPE_SUCCESS'
export const REMOVE_RECIPE_FAILED = 'REMOVE_RECIPE_FAILED'

export const UPDATE_RECIPE_PENDING = 'UPDATE_RECIPE_PENDING'
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS'
export const UPDATE_RECIPE_FAILED = 'UPDATE_RECIPE_FAILED'

export const BASE_URL = `http://localhost:5432/recipes-api`